### ISSUE TITLE
Restarting the container exiting the sql edge

### ISSUE THREAD

**Issue by thunder-007** [Azure/azure-service-bus-emulator-installer#36]
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/task/148/fdinfo': Permission denied
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/task/149/fdinfo': Permission denied
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/task/150/fdinfo': Permission denied
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/task/151/fdinfo': Permission denied
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/task/152/fdinfo': Permission denied
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/task/153/fdinfo': Permission denied
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/task/154/fdinfo': Permission denied
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/task/155/fdinfo': Permission denied
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/map_files': Permission denied
2024-11-24 19:03:19 /usr/bin/find: '/proc/26/fdinfo': Permission denied
2024-11-24 19:03:19 dmesg: read kernel buffer failed: Operation not permitted
2024-11-24 19:03:19 /usr/bin/timeout: failed to run command '/bin/journalctl': No such file or directory
2024-11-24 19:03:19 /usr/bin/timeout: failed to run command '/bin/journalctl': No such file or directory
2024-11-24 19:03:20 2024/11/24 13:33:20 [launchpadd] WARNING: Failed to connect to SQL because: dial tcp [::1]:1431: connect: connection refused, will reattempt connection.
2024-11-24 19:03:19 Sun Nov 24 13:33:19 UTC 2024 Capturing program information
2024-11-24 19:03:19 Dump already generated: /var/opt/mssql/log/core.sqlservr.11_24_2024_13_33_18.26, moving to /var/opt/mssql/log/core.sqlservr.26.temp/core.sqlservr.26.gdmp
2024-11-24 19:03:19 Moving logs to /var/opt/mssql/log/core.sqlservr.26.temp/log/paldumper-debug.log
2024-11-24 19:03:19 Sun Nov 24 13:33:19 UTC 2024 Capturing program binaries
2024-11-24 19:03:20 Sun Nov 24 13:33:20 UTC 2024 Not compressing the dump files, moving instead to: /var/opt/mssql/log/core.sqlservr.11_24_2024_13_33_19.26.d

```
(.venv) thunder@thunderbook service_bus_emulator % docker-compose up -d
[+] Running 3/3
 ✔ Network microsoft-azure-servicebus-emulator_sb-emulator  Created                                                                                                        0.0s 
 ✔ Container sqledge                                        Started                                                                                                        0.2s 
 ✔ Container servicebus-emulator                            Started                                                                                                        0.3s 
(.venv) thunder@thunderbook service_bus_emulator % docker-compose stop 
[+] Stopping 2/1
 ✔ Container servicebus-emulator  Stopped                                                                                                                                  0.1s 
 ✔ Container sqledge              Stopped                                                                                                                                  0.0s 
(.venv) thunder@thunderbook service_bus_emulator % docker-compose up -d
[+] Running 2/2
 ✔ Container sqledge              Started                                                                                                                                  0.1s 
 ✔ Container servicebus-emulator  Started                                                                                                                                  0.2
```
```
name: microsoft-azure-servicebus-emulator
services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "./config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "MyPassword$6783!"
      ACCEPT_EULA: "Y"
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
        container_name: "sqledge"
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        networks:
          sb-emulator:
            aliases:
              - "sqledge"
        environment:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "MyPassword$6783!"
networks:
  sb-emulator:
```
