### ISSUE TITLE
Drop MSSQL (or others) as a dependency

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-service-bus-emulator-installer#55]
_**Preface: I am genuinely interested in being able to adopt Azure Service Bus! [I advocated for a solid local emulator option quite some while back!](https://github.com/Azure/azure-service-bus/issues/223#issuecomment-493717070) So don't get any bad ideas here.**_

Sadly, a dependency as heavy as a database should have been caught early on in the analysis phases. It's a problem that the Azure Storage group already faced and is what resulted in them favouring the external Azurite project over the official MS Storage Emulator.

_(Really, you guys could have just reached out to me. I'd have told you how much of a deal breaker this would have been.)_

If I'm running postgres as my database, I don't want to also run the heavy mssql DB container just to get another services local emulator running!

Get rid of this dependency but please....don't make us wait another twelve years for it. 🙏

**Comment by sebastienros** [comment]
I don't think the emulator uses MSSQL right now, but I could be wrong, or "MSSQL" could mean many things too. When executed locally it starts [Sql Edge](https://learn.microsoft.com/en-us/azure/azure-sql-edge/disconnected-deployment) because it's more portable (works on ARM64).

**Comment by Saglodha** [comment]
Thanks for sharing your thoughts @atrauzzi . Our decision to depend on SQL edge was made after evaluation of various internal factors. We do not have any short-term plans to drop this dependency. 

I'm interested in understanding the heaviness you observe while running service bus emulator as end user. Would you mind sharing more details about your test setup?

**Comment by mlanglet** [comment]
> whats the plan for replacement given sql edge's retirement? https://azure.microsoft.com/en-us/updates?id=azure-sql-edge-retirement

In our project we're using mssql as replacement. In fact, edge wouldn't work for us in the first place so we use mssql container as drop in replacement. It's heavy sure, but it works..

Sample from our system test setup compose file:
```
  service-bus:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: service-bus-data
      MSSQL_SA_PASSWORD: "whatevermeetstheirpolicyrules!L0l"
      ACCEPT_EULA: Y
    depends_on:
      - service-bus-data
  service-bus-data:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "whatevermeetstheirpolicyrules!L0l"
```
