### ISSUE TITLE
Healthcheck not accessable from within the container

### ISSUE THREAD

**Issue by michael-cavanaugh** [Azure/azure-service-bus-emulator-installer#88]
**Describe the bug**
The service bus emulator team recently created a HealthCheck for the service bus emulator and while this HealthCheck works great from the host it does not work at all to satisfy the needs of a docker compose HealthCheck or any HealthCheck that requires that the container execute the HealthCheck on itself. wget, curl, sh, and bash are all unavailable on the minimal container. Please provide something so this HealthCheck can work and we don't have to wrap your image with our custom image.

**To Reproduce**
Add the following to a docker compose file
```
servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: ${TENANT_ID}-servicebus-emulator
    ports:
      - "5672:5672"
      - "5300:5300"
      - "8021:8080"
    environment:
      - ACCEPT_EULA=Y
      - SQL_SERVER=sqlserver
      - MSSQL_SA_PASSWORD=${TENANT_DB_PASSWORD}
    volumes:
      - "./Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -f http://localhost:5300/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - tenant-network
    depends_on:
      sqlserver:
        condition: service_healthy
```
it will always fail a health check even when it passes locally from the host

**Expected behavior**
I expect Docker Compose to be able to recognize this service as healthy so i can properly setup the dependencies. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/db96c67f-2016-4cc0-82d6-58774e4fdcb6)

**Logs**
If applicable, add the logs generated from the container.
```
     Emulator Service is Successfully Up! ; Use connection string: "Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;". For more networking-options refer: "https://github.com/Azure/azure-service-bus-emulator-installer?tab=readme-ov-file#interact-with-the-emulator"
```

**Desktop:**
 - OS: Windows using Rancher Desktop

**Image Platform-Architecture Used:**
- Linux-amd64

**Arguments && Environment variables to start Emulator:**
- ACCEPT_EULA: Y
- CONFIG_PATH: ./Config.json

**Emulator Launch Method:**
 - Direct Docker compose

**Additional context:**
```
 MichaelCavanaugh   ~    docker exec -it AUDIUS-servicebus-emulator bash                                                                                                                                                                                                                                      in pwsh at 21:22:39
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
 MichaelCavanaugh   ~    docker exec -it AUDIUS-servicebus-emulator bash                                                                                                                                                                                                                                      in pwsh at 21:22:42
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
 MichaelCavanaugh   ~    docker exec -it AUDIUS-servicebus-emulator bash                                                                                                                                                                                                                                      in pwsh at 21:22:47
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
 MichaelCavanaugh   ~    docker exec -it AUDIUS-servicebus-emulator sh                                                                                                                                                                                                                                        in pwsh at 21:23:04
OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown
 MichaelCavanaugh   ~    docker exec AUDIUS-servicebus-emulator curl -vvv http://localhost:5300/health                                                                                                                                                                                                        in pwsh at 21:23:21
OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
 MichaelCavanaugh   ~    docker exec AUDIUS-servicebus-emulator wget -qO- http://localhost:5300/health                                                                                                                                                                                                        in pwsh at 21:23:34
OCI runtime exec failed: exec failed: unable to start container process: exec: "wget": executable file not found in $PATH: unknown
 MichaelCavanaugh   ~    curl -vvv http://localhost:5300/health                                                                                                                                                                                                                                               in pwsh at 21:24:00
* Host localhost:5300 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:5300...
* Connected to localhost (::1) port 5300
> GET /health HTTP/1.1
> Host: localhost:5300
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Tue, 29 Apr 2025 01:24:20 GMT
< Server: Kestrel
< Transfer-Encoding: chunked
<
{"status":"healthy","message":"Service is healthy."}* Connection #0 to host localhost left intact
```
