### ISSUE TITLE
Unable to read messages from Topic/Subscription

### ISSUE THREAD

**Issue by TylerHaigh** [Azure/azure-service-bus-emulator-installer#91]
**Describe the bug**
Unable to read messages from Topic/Subscription

**To Reproduce**
1. Use the [sample Config.json provided](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/ServiceBus-Emulator/Config/Config.json)
2. Use the [sample docker-compose provided](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/Docker-Compose-Template/docker-compose-default.yml)
3. Refer to the below code snippet (adapted from [sample provided](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/Sample-Code-Snippets/JS/azure-service-bus-emulator-node-sample/sample-send-receive.js):

```
const { ServiceBusClient } = require("@azure/service-bus");

// Connection string and queue name
const connectionString = "Endpoint=sb://127.0.0.1;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;";
const queueName = "queue.1";
const topicName = "topic.1"
const subscriptionName = ["subscription.1", "subscription.2", "subscription.3", "subscription.4"]

// Create a ServiceBusClient
const sbClient = new ServiceBusClient(connectionString);

// Sending a message
async function sendMessage() {
  const sender = sbClient.createSender(queueName);
  const message = { body: "Hello, Service Bus!" };
  await sender.sendMessages({...message, properties: { prop1: "value1" }});
  console.log("Message sent!");

  sbClient.createSender(topicName);
  await sender.sendMessages({...message, properties: { prop1: "value1" }});

  console.log("Message sent!");
  await sender.close();
}

// Receiving a message
async function receiveMessage() {
  const receiver = sbClient.createReceiver(queueName);
  const messages = await receiver.receiveMessages(1, { maxWaitTimeInMs: 5000 });
  for (const message of messages) {
    console.log(`Received: ${message.body}`);
    await receiver.completeMessage(message);
  }
  await receiver.close();


  for (const sub of subscriptionName) {

    const topicSubscriber = sbClient.createReceiver(topicName, sub);
    console.log(`Listening to topic ${topicName} with subscription ${sub}`);
    const topicMessages = await topicSubscriber.receiveMessages(1, { maxWaitTimeInMs: 5000 });
    for (const message of topicMessages) {
        console.log(`Received from topic ${sub}: ${message.body}`);
        await topicSubscriber.completeMessage(message);
    }
    await topicSubscriber.close();
  }
}

// Main function to send and receive messages
async function main() {
  await sendMessage();
  await receiveMessage();
  await sbClient.close();
}

main().catch((err) => {
  console.error("Error occurred: ", err);
  process.exit(1);
});
```

Log output:

```
$ node .\index.js
Message sent!
Message sent!
Received: Hello, Service Bus!
Listening to topic topic.1 with subscription subscription.1
Listening to topic topic.1 with subscription subscription.2
Listening to topic topic.1 with subscription subscription.3
Listening to topic topic.1 with subscription subscription.4
```

**Expected behavior**
At least one subscription to return a message

**Screenshots**

**Logs**
Can provide  if required

**Desktop:**
 - OS:  Windows / WSL 2 (Ubuntu 24.04)

```
$ uname -a
Linux <HOST> 6.6.87.1-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Mon Apr 21 17:08:54 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.2 LTS
Release:        24.04
Codename:       noble
```

**Image Platform-Architecture Used:**
- Linux-amd64

**Docker Version:**
- Docker Desktop Version (If applicable): 
- Docker Engine Version: Docker version 28.1.1, build 4eba377

**Arguments && Environment variables to start Emulator:**
- ACCEPT_EULA: Y
- CONFIG_PATH: .compose/service-bus/Config.json

**Emulator Launch Configuration:**
- [sample docker-compose provided](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/Docker-Compose-Template/docker-compose-default.yml)

**Emulator Launch Method:**
 - Direct Docker compose

```
name: microsoft-azure-servicebus-emulator
services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - ".compose/service-bus/Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"  # Password should be same as what is set for SQL Edge
      ACCEPT_EULA: Y
      # SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL} # Optional: Time in seconds to wait for SQL to be ready (default is 15 seconds)
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
        container_name: "sqledge"
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        networks:
          sb-emulator:
            aliases:
              - "sqledge"
        environment:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"

networks:
  sb-emulator:

```

**Additional context:**
